Insert into USUARIO ( NOME_COMPLETO,SENHA,LOGIN,AUTORIZACAO) values ( 'Clecio Rocha','$2a$10$7bh15Hd48SlfAp8Gn/W6meCmisaAh5G4.j1VbVOpJDOSNAa9QESHO','Admin','ROLE_ADMIN');
Insert into USUARIO ( NOME_COMPLETO,SENHA,LOGIN,AUTORIZACAO) values ( 'Scrum','$2a$10$ifYCuc.Ml/OFmoA0TIFf9ORDpl0vUF0lb8MdSSken45Mbj75y6NaS','Scrum','ROLE_USER');
Insert into TECNOLOGIA (NOME_TECNOLOGIA ,DESCRICAO) values ('Java','Spring Boot Applications');
Insert into TECNOLOGIA (NOME_TECNOLOGIA ,DESCRICAO) values ('.Net','C# Applications');
Insert into TECNOLOGIA (NOME_TECNOLOGIA ,DESCRICAO) values ('Phyton','I.A');
Insert into DAILY_STATUS (STATUS) values ('Fazendo');
Insert into DAILY_STATUS (STATUS) values ('Feito');
Insert into DAILY_STATUS (STATUS) values ('Nda');
Insert into PROGRAMA_START (NOME_PROGRAMA,DATA_INICIAL,DATA_FINAL) values ('Starter#1','2022-01-12','2022-05-12');
Insert into PROGRAMA_START (NOME_PROGRAMA,DATA_INICIAL,DATA_FINAL) values ('Starter#2','2022-05-12','2022-07-12');
Insert into PROGRAMA_START (NOME_PROGRAMA,DATA_INICIAL,DATA_FINAL) values ('Starter#3','2022-08-12','2022-12-12');
Insert into SCRUM_MASTER (NOME) values ('Felipe Rodrigues de Almeida');
Insert into SCRUM_MASTER (NOME) values ('Rodrigo Xavier Pereira');
Insert into SCRUM_MASTER (NOME) values ('Ricardo Silva');
insert into MODULO (NOME_MODULO, PROJETO) values ('MVC', 'DESAFIO MVC');
insert into MODULO (NOME_MODULO, PROJETO) values ('API', 'DESAFIO API');
Insert into GRUPO(NOME_GRUPO) values ('GRUPO #1');
UPDATE GRUPO SET MODULO_ID = 1 WHERE ID = 1;
UPDATE GRUPO SET SCRUM_MASTER_ID = 1 WHERE ID = 1;
UPDATE GRUPO SET TECNOLOGIA_ID = 1 WHERE ID = 1;
Insert into GRUPO(NOME_GRUPO) values ('GRUPO #2');
UPDATE GRUPO SET MODULO_ID = 2 WHERE ID = 2;
UPDATE GRUPO SET SCRUM_MASTER_ID = 2 WHERE ID = 2;
UPDATE GRUPO SET TECNOLOGIA_ID = 2 WHERE ID = 2;
insert into STARTER (NOME , QUATRO_LETRAS ,IMAGEM ) VALUES ('José Henrique Medeiros' ,'JHME', 'https://media.istockphoto.com/photos/mature-businessman-looking-out-of-window-picture-id1207054663?k=20&m=1207054663&s=612x612&w=0&h=F7dA43Q4TmGcNJMWGj7ldZEnqzt6SZoqntaTy12a6fc=');
UPDATE STARTER SET GRUPO_ID = 1  WHERE ID = 1;
UPDATE STARTER SET PROGRAMA_START_ID  = 1  WHERE ID = 1;
insert into STARTER (NOME , QUATRO_LETRAS ,IMAGEM ) VALUES ('Amanda Ribeiro Cordeiro' ,'ARCD', 'https://media.istockphoto.com/photos/hispanic-female-business-professional-in-office-boardroom-picture-id1272687005?k=20&m=1272687005&s=612x612&w=0&h=Dl4A6cViDPHr7BLSDNvt31S6ldvTyg9CNAFxWrayGYw=');
UPDATE STARTER SET GRUPO_ID = 2  WHERE ID = 2;
UPDATE STARTER SET PROGRAMA_START_ID  = 2  WHERE ID = 2;
insert into STARTER (NOME , QUATRO_LETRAS ,IMAGEM ) VALUES ('Pedro Lima ' ,'PLMA', 'https://media.istockphoto.com/photos/young-handsome-business-man-dressed-in-casual-denim-shirt-with-on-picture-id1170154554?k=20&m=1170154554&s=612x612&w=0&h=VstOlFseQ3wHbs1X3e9JZDZh97g07XfnqsibvTDIAWs=');
UPDATE STARTER SET GRUPO_ID = 1  WHERE ID = 3;
UPDATE STARTER SET PROGRAMA_START_ID  = 2  WHERE ID = 3;
Insert into DAILY (DATA ,SIM, IMPEDIMENTOS, OBSERVACAO) VALUES ('2021-12-02','TRUE','Problemas de Internet','Chegou atrasado e camera desligada');
UPDATE DAILY SET MODULO_ID=1,STARTER_ID =1,STATUS_ID=1 WHERE ID=1;
Insert into DAILY (DATA ,SIM, IMPEDIMENTOS, OBSERVACAO) VALUES ('2021-12-02','TRUE','Falhas com banco de dados','');
UPDATE DAILY SET MODULO_ID=1,STARTER_ID = 2,STATUS_ID=1 WHERE ID=2;
Insert into AVALIACAO (NOTA_DE_AVALIACAO,OBSERVACAO) VALUES ('10','Projeto muito bem estruturado');
UPDATE AVALIACAO SET MODULO_ID=1, STARTER_ID =1 WHERE ID = 1;
Insert into AVALIACAO (NOTA_DE_AVALIACAO,OBSERVACAO) VALUES ('8','Faltam detalhes');
UPDATE AVALIACAO SET MODULO_ID=1, STARTER_ID =2 WHERE ID = 2;


